### ISSUE TITLE
confusion around process for addition/removal of CB members

### ISSUE THREAD

**Issue by jlipps** [jquery-foundation/CB#1]
From https://github.com/jquery-foundation/CB/blob/master/CB-Charter.md, I see the following two statements:

1. > The CB may add additional members to the CB by a standard CB motion and vote. A CB member may be removed from the CB by voluntary resignation, or by a standard CB motion.

2. > If an agenda item cannot reach a consensus a TSC/CB member can call for either a closing vote or a vote to table the issue to the next meeting. The call for a vote must be seconded by a majority of the TSC/CB or else the discussion will continue. Simple majority wins, with the following exceptions, which will require the affirmative vote of two-thirds of the members of the CB to pass

Section two includes adding/removing CB members. I was a little confused; what is the "standard CB motion"---is that the "consensus seeking process"? But if so, why is this particular topic mentioned as a special exception to a vote in lieu of consensus? I guess my confusion is about what a "standard CB motion" is. Is that the same thing or a different thing than described in (2)?

**Comment by kborchers** [comment]
Hmm, I do see how this can be confusing. When it comes to CB and TSC membership, those are elections and follow the process in [section 7](https://github.com/jquery-foundation/CB/blob/master/CB-Charter.md#section-7-elections).

I think [section 8's](https://github.com/jquery-foundation/CB/blob/master/CB-Charter.md#section-8-voting) title needs to be clarified as well as maybe some additional explanation that this is only describing the decision making process. It might even make sense to remove the member addition/removal exception from that section since that falls into elections, not decision making.

Any opinions on clarification?

**Comment by jlipps** [comment]
@kborchers I think just removing the addition/removal exception makes most sense if it's covered elsewhere in a more clear context. Additional explanation about this being specifically related to "decision-making" and not "elections" would be helpful, as that distinction was not immediately clear to me
